stages:
  - migration

docker build:
  stage: migration
  tags:
    - compile
  script:
    - find migration/db/ -type f
    - find migration/db/ -type f | xargs cat > migration/combine_file.txt && md5sum migration/combine_file.txt | awk '{print $1}' > migration/md5
    - cat migration/md5
    - docker build -f migration/Dockerfile -t www.xk.docker-registry.com:5501/migration:`cat migration/md5` migration/
    - docker push www.xk.docker-registry.com:5501/migration:`cat migration/md5`
    - docker rm -f migration || echo "No running migration task"
    - echo "docker run --net=host -v /var/logs/liquibase:/var/logs/liquibase --name migration www.xk.docker-registry.com:5501/migration:`cat migration/md5` postgres $MIGRATION_PG_PASSWORD $MIGRATION_PG_URL 0"
    - docker run --net=host -v /var/logs/liquibase:/var/logs/liquibase --name migration www.xk.docker-registry.com:5501/migration:`cat migration/md5` postgres $MIGRATION_PG_PASSWORD $MIGRATION_PG_URL 0

