stages:
  - build_image

docker build:
  stage: build_image
  tags:
    - compile
  script:
    - find migration/db/ -type f | xargs cat > combine_file.txt && md5sum combine_file.txt | awk '{print $1}' > md5
    - docker build -f migration/Dockerfile -t migration:v1 migration/

